apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  serviceAccountName: read-only-sa
  containers:
  - name: demo
    image: nginx:1.14.2
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USER
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASS
    - name: APP_MODE
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: APP_MODE
    ports:
    - containerPort: 80
